/**
 * Agent Kit Catalog — данные об MCP, скиллах, плагинах.
 *
 * Структура каждой записи:
 * - slug: URL-safe идентификатор
 * - name: отображаемое имя
 * - description: 1-2 предложения
 * - category: ai | freelance | telegram | code | deploy | docs | design | ru-market | skill | plugin
 * - tags: массив ключевых слов
 * - url: ссылка (GitHub репо или NuGet/Marketplace)
 * - tools / count: число tools/скиллов/плагинов
 * - stack: технологии
 * - featured: bool для "★ featured"
 * - install: команда установки
 * - icon: emoji или путь
 */

// ===== MCP Servers (22) =====
const MCPS = [
  {
    slug: "kwork-gig-studio",
    name: "Kwork Gig Studio",
    description: "Единый MCP для создания и публикации кворков на Kwork: ниша → обложка → текст → FAQ → публикация. Open source, MIT.",
    category: "freelance",
    tags: ["kwork", "фриланс", "AI-аудит", "обложка", "vision-чекер"],
    url: "https://github.com/shekelstrong/kwork-gig-studio",
    tools: 5,
    stack: "Python 3.11+",
    featured: true,
    install: "git clone https://github.com/shekelstrong/kwork-gig-studio && cd kwork-gig-studio && pip install -r requirements.txt",
    icon: "🎨",
  },
  {
    slug: "hh-apply-suite",
    name: "HH Apply Suite",
    description: "Парсинг вакансий hh.ru, ресёрч GitHub, адаптация сопровода под ATS, ответы на 12 типовых HR-вопросов.",
    category: "freelance",
    tags: ["hh.ru", "vacancy", "ATS", "cover-letter", "HR"],
    url: "https://github.com/shekelstrong/hh-apply-suite",
    tools: 5,
    stack: "Python 3.11+",
    install: "git clone https://github.com/shekelstrong/hh-apply-suite && cd hh-apply-suite && pip install -r requirements.txt",
    icon: "💼",
  },
  {
    slug: "freelance-launcher",
    name: "Freelance Launcher",
    description: "Запуск фрилансера с нуля. Портфолио + кворки + постинг в TenChat/VC/YouTube. Готовые шаблоны HTML.",
    category: "freelance",
    tags: ["фриланс", "портфолио", "TenChat", "VC", "YouTube"],
    url: "https://github.com/shekelstrong/freelance-launcher",
    tools: 5,
    stack: "Python 3.11+",
    install: "git clone https://github.com/shekelstrong/freelance-launcher && cd freelance-launcher && pip install -r requirements.txt",
    icon: "🚀",
  },
  {
    slug: "freelance-revenue-kit",
    name: "Freelance Revenue Kit",
    description: "Стратегии дохода: план первого дохода за 7 дней, параллельные каналы (Kwork/Plati/LolzTeam), экстренные стратегии.",
    category: "freelance",
    tags: ["доход", "Kwork", "Plati", "LolzTeam", "TenChat"],
    url: "https://github.com/shekelstrong/freelance-revenue-kit",
    tools: 4,
    stack: "Python 3.11+",
    install: "git clone https://github.com/shekelstrong/freelance-revenue-kit && cd freelance-revenue-kit && pip install -r requirements.txt",
    icon: "💰",
  },
  {
    slug: "ai-agent-factory",
    name: "AI Agent Factory",
    description: "Конструктор AI-агентов через n8n. Описание задачи → n8n workflow → деплой → мониторинг. 3 готовых шаблона.",
    category: "ai",
    tags: ["AI-agent", "n8n", "workflow", "OpenRouter"],
    url: "https://github.com/shekelstrong/ai-agent-factory",
    tools: 5,
    stack: "Python 3.11+ + n8n",
    featured: true,
    install: "git clone https://github.com/shekelstrong/ai-agent-factory && cd ai-agent-factory && pip install -r requirements.txt",
    icon: "🤖",
  },
  {
    slug: "agent-to-prod",
    name: "Agent to Prod",
    description: "AI-агент от ТЗ до production. Системный дизайн, MVP за 4 недели, чек-лист прод-деплоя, мониторинг, пост-мортем.",
    category: "ai",
    tags: ["production", "monitoring", "scale", "post-mortem"],
    url: "https://github.com/shekelstrong/agent-to-prod",
    tools: 6,
    stack: "Python 3.11+",
    install: "git clone https://github.com/shekelstrong/agent-to-prod && cd agent-to-prod && pip install -r requirements.txt",
    icon: "⚡",
  },
  {
    slug: "llm-reliability-kit",
    name: "LLM Reliability Kit",
    description: "Надёжность LLM: парсинг ответов (JSON/XML/text), fallback-цепочки провайдеров, выбор по cost/latency/quality, retry-стратегии.",
    category: "ai",
    tags: ["LLM", "fallback", "retry", "OpenAI", "Anthropic"],
    url: "https://github.com/shekelstrong/llm-reliability-kit",
    tools: 5,
    stack: "Python 3.11+",
    install: "git clone https://github.com/shekelstrong/llm-reliability-kit && cd llm-reliability-kit && pip install -r requirements.txt",
    icon: "🛡️",
  },
  {
    slug: "llm-unit-econ",
    name: "LLM Unit Economics",
    description: "Юнит-экономика LLM-продукта. Стоимость токенов 10 моделей, gross/net margin, break-even, сравнение 9 провайдеров, pricing table.",
    category: "ai",
    tags: ["юнит-экономика", "tokens", "margin", "провайдеры"],
    url: "https://github.com/shekelstrong/llm-unit-econ",
    tools: 5,
    stack: "Python 3.11+",
    install: "git clone https://github.com/shekelstrong/llm-unit-econ && cd llm-unit-econ && pip install -r requirements.txt",
    icon: "📊",
  },
  {
    slug: "hermes-memory-pro",
    name: "Hermes Memory Pro",
    description: "Премиум memory layer: сжатие контекста, RAG-поиск по кодбазе, knowledge base, observations, wiki-builder.",
    category: "ai",
    tags: ["memory", "RAG", "knowledge-base", "wiki"],
    url: "https://github.com/shekelstrong/hermes-memory-pro",
    tools: 7,
    stack: "Python 3.11+",
    install: "git clone https://github.com/shekelstrong/hermes-memory-pro && cd hermes-memory-pro && pip install -r requirements.txt",
    icon: "🧠",
  },
  {
    slug: "telegram-suite",
    name: "Telegram Suite",
    description: "Telegram-боты (aiogram 3) и Mini Apps. Шаблоны, деплой через Docker, отладка WebApp, форматирование, навигация по категориям.",
    category: "telegram",
    tags: ["telegram", "aiogram", "Mini App", "Docker"],
    url: "https://github.com/shekelstrong/telegram-suite",
    tools: 5,
    stack: "Python 3.11+ + aiogram 3",
    featured: true,
    install: "git clone https://github.com/shekelstrong/telegram-suite && cd telegram-suite && pip install -r requirements.txt",
    icon: "✈️",
  },
  {
    slug: "vk-tg-bridge",
    name: "VK-TG Bridge",
    description: "Мост VK → Telegram. Парсинг постов VK API, фильтрация, форматирование HTML, end-to-end пайплайн с отправкой.",
    category: "telegram",
    tags: ["VK", "Telegram", "мост", "парсинг"],
    url: "https://github.com/shekelstrong/vk-tg-bridge",
    tools: 4,
    stack: "Python 3.11+",
    install: "git clone https://github.com/shekelstrong/vk-tg-bridge && cd vk-tg-bridge && pip install -r requirements.txt",
    icon: "🌉",
  },
  {
    slug: "engineering-playbook",
    name: "Engineering Playbook",
    description: "TDD red-green-refactor, 4-phase debugging, DDD ubiquitous language, архитектурное ревью, PRD → GitHub issues.",
    category: "code",
    tags: ["TDD", "debugging", "DDD", "PRD", "refactoring"],
    url: "https://github.com/shekelstrong/engineering-playbook",
    tools: 5,
    stack: "Python 3.11+ + TypeScript",
    install: "git clone https://github.com/shekelstrong/engineering-playbook && cd engineering-playbook && pip install -r requirements.txt",
    icon: "🔧",
  },
  {
    slug: "code-craft-suite",
    name: "Code Craft Suite",
    description: "Качество кода: 4-phase debugging, планирование фичи, декомпозиция задач, рефакторинг, KB-аудит, suggestions по упрощению.",
    category: "code",
    tags: ["debugging", "refactoring", "KB-audit", "simplify"],
    url: "https://github.com/shekelstrong/code-craft-suite",
    tools: 6,
    stack: "Python 3.11+",
    install: "git clone https://github.com/shekelstrong/code-craft-suite && cd code-craft-suite && pip install -r requirements.txt",
    icon: "✨",
  },
  {
    slug: "repo-auditor",
    name: "Repo Auditor",
    description: "Аудит GitHub-репозиториев: структура, качество кода (тесты/CI/docs), честность README, verdict (use/caution/avoid).",
    category: "code",
    tags: ["github", "audit", "quality", "honesty"],
    url: "https://github.com/shekelstrong/repo-auditor",
    tools: 5,
    stack: "Python 3.11+",
    install: "git clone https://github.com/shekelstrong/repo-auditor && cd repo-auditor && pip install -r requirements.txt",
    icon: "🔍",
  },
  {
    slug: "deploy-stack",
    name: "Deploy Stack",
    description: "Деплой Python-сервисов и фронтендов: VPS (Docker + GitHub Actions), Vercel, Layero. Готовые Dockerfile и vercel.json.",
    category: "deploy",
    tags: ["Docker", "GitHub Actions", "VPS", "Vercel", "Layero"],
    url: "https://github.com/shekelstrong/deploy-stack",
    tools: 6,
    stack: "Python 3.11+ + Docker",
    install: "git clone https://github.com/shekelstrong/deploy-stack && cd deploy-stack && pip install -r requirements.txt",
    icon: "🚀",
  },
  {
    slug: "landing-launcher",
    name: "Landing Launcher",
    description: "Лендинг от ТЗ до деплоя. Ресёрч конкурентов, copy (3 тона: professional/casual/bold), layout (4 типа), деплой на Vercel/Layero.",
    category: "deploy",
    tags: ["landing", "Vercel", "Layero", "copy", "layout"],
    url: "https://github.com/shekelstrong/landing-launcher",
    tools: 5,
    stack: "Python 3.11+ + Vite/Next.js",
    install: "git clone https://github.com/shekelstrong/landing-launcher && cd landing-launcher && pip install -r requirements.txt",
    icon: "🎯",
  },
  {
    slug: "infra-security-scan",
    name: "Infra Security Scan",
    description: "Security scan инфраструктуры. Linux через SSH (ps/ss/passwd/cron), Windows через PowerShell, GitHub org. IOC + report.",
    category: "deploy",
    tags: ["security", "Linux", "Windows", "GitHub", "IOC"],
    url: "https://github.com/shekelstrong/infra-security-scan",
    tools: 5,
    stack: "Python 3.11+",
    install: "git clone https://github.com/shekelstrong/infra-security-scan && cd infra-security-scan && pip install -r requirements.txt",
    icon: "🛡️",
  },
  {
    slug: "doc-factory",
    name: "Doc Factory",
    description: "Генерация документов: PDF (cyrillic), DOCX, PPTX, XLSX из markdown. Графики через matplotlib, авто-детект кириллицы.",
    category: "docs",
    tags: ["PDF", "DOCX", "PPTX", "XLSX", "cyrillic"],
    url: "https://github.com/shekelstrong/doc-factory",
    tools: 6,
    stack: "Python 3.11+ + reportlab + python-docx",
    install: "git clone https://github.com/shekelstrong/doc-factory && cd doc-factory && pip install -r requirements.txt",
    icon: "📄",
  },
  {
    slug: "youtube-studio",
    name: "YouTube Studio",
    description: "YouTube-креатор: транскрипты, сценарии (hook/intro/main/CTA), thumbnails, реверс-инжиниринг viral видео, идеи по нише.",
    category: "docs",
    tags: ["YouTube", "транскрипт", "сценарий", "thumbnail", "viral"],
    url: "https://github.com/shekelstrong/youtube-studio",
    tools: 5,
    stack: "Python 3.11+",
    install: "git clone https://github.com/shekelstrong/youtube-studio && cd youtube-studio && pip install -r requirements.txt",
    icon: "🎬",
  },
  {
    slug: "visual-studio",
    name: "Visual Studio",
    description: "Визуальный контент: p5.js алгоритмический арт, SVG/Excalidraw диаграммы, ASCII-арт, пиксель-арт с ретро-палитрами.",
    category: "docs",
    tags: ["p5.js", "SVG", "Excalidraw", "ASCII", "pixel-art"],
    url: "https://github.com/shekelstrong/visual-studio",
    tools: 4,
    stack: "Python 3.11+ + pyfiglet",
    install: "git clone https://github.com/shekelstrong/visual-studio && cd visual-studio && pip install -r requirements.txt",
    icon: "🎨",
  },
  {
    slug: "design-system-mcp",
    name: "Design System MCP",
    description: "UI-ревью: 5 направлений критики, design tokens (CSS/Tailwind/SCSS), WCAG a11y, поиск UI-паттернов, спецификация компонентов.",
    category: "design",
    tags: ["UI", "design-system", "a11y", "WCAG", "Dieter Rams"],
    url: "https://github.com/shekelstrong/design-system-mcp",
    tools: 6,
    stack: "Python 3.11+",
    install: "git clone https://github.com/shekelstrong/design-system-mcp && cd design-system-mcp && pip install -r requirements.txt",
    icon: "🎭",
  },
  {
    slug: "ru-ai-saas-template",
    name: "RU AI SaaS Template",
    description: "Архитектурный шаблон AI-SaaS для РФ: Supabase + OpenRouter + Layero + ЮKassa + Cryptobot + Telegram Stars. Документы по 152-ФЗ.",
    category: "ru-market",
    tags: ["РФ", "Supabase", "ЮKassa", "Cryptobot", "152-ФЗ"],
    url: "https://github.com/shekelstrong/ru-ai-saas-template",
    tools: 5,
    stack: "Python 3.11+ + FastAPI + Supabase",
    install: "git clone https://github.com/shekelstrong/ru-ai-saas-template && cd ru-ai-saas-template && pip install -r requirements.txt",
    icon: "🇷🇺",
  },
];

// ===== Hermes Skills (156) — метаданные для каталога =====
// Примеры самых важных групп (полный список в skills/)
const SKILLS_GROUPS = [
  {
    group: "Kwork",
    count: 7,
    skills: ["kwork-gig-studio", "kwork-cover-design", "kwork-cover-generator", "kwork-cover-image", "kwork-gig-creation", "kwork-tos-rules", "kwork-parallel-channels"],
    description: "Создание кворков, обложки, TOS, parallel-каналы",
    category: "freelance",
  },
  {
    group: "Telegram",
    count: 8,
    skills: ["telegram-bot-aiogram", "telegram-bot-best-practices", "telegram-bot-catalog-navigation", "telegram-bot-docker-deploy", "telegram-output-style", "telegram-mini-app-frontend-debugging"],
    description: "aiogram 3, Mini Apps, деплой, отладка",
    category: "telegram",
  },
  {
    group: "HH / Vacancy",
    count: 6,
    skills: ["vacancy-response-writing", "cover-letter-tech-vacancy", "hh-vacancy-parser", "hh-vacancy-cover-letter"],
    description: "Парсинг вакансий, ATS-сопроводы, ответы HR",
    category: "freelance",
  },
  {
    group: "n8n / Workflows",
    count: 5,
    skills: ["n8n-code-javascript", "n8n-code-python", "n8n-expression-syntax", "n8n-mcp-tools-expert", "n8n-node-configuration"],
    description: "JavaScript/Python в n8n, expressions, MCP tools",
    category: "ai",
  },
  {
    group: "AI Agents",
    count: 5,
    skills: ["autonomous-ai-agents", "claude-code", "codex", "supergoal", "opencode"],
    description: "Claude Code, Codex, делегирование задач",
    category: "ai",
  },
  {
    group: "Designer (60+)",
    count: 60,
    skills: ["ui-design", "ux-design", "color-system", "typography-scale", "accessibility-audit", "motion-system", "naming-convention", "..."],
    description: "UI/UX, design tokens, a11y, motion, паттерны",
    category: "design",
  },
  {
    group: "Matt Pocock TypeScript",
    count: 15,
    skills: ["ask-matt", "codebase-design", "diagnosing-bugs", "domain-modeling", "implement", "improve-codebase-architecture", "prototype", "tdd", "to-issues", "to-prd", "triage", "..."],
    description: "TDD, domain modeling, PRD, рефакторинг",
    category: "code",
  },
  {
    group: "LLM Ops",
    count: 4,
    skills: ["llm-response-parsing", "llm-inference-ops", "gen-ai-provider-ops", "huggingface-hub"],
    description: "Парсинг, inference, провайдеры",
    category: "ai",
  },
  {
    group: "Memory & Knowledge",
    count: 5,
    skills: ["headroom", "codebase-memory-mcp", "kb-brain-restructure", "llm-wiki", "obsidian"],
    description: "Сжатие контекста, RAG, KB, wiki",
    category: "ai",
  },
  {
    group: "Telegram-Output-Style",
    count: 1,
    skills: ["telegram-output-style"],
    description: "Стиль ответов для Telegram (компактные списки)",
    category: "telegram",
  },
  {
    group: "Kwork Cover Design",
    count: 4,
    skills: ["kwork-cover-design", "kwork-cover-generator", "kwork-cover-image", "kwork-tos-rules"],
    description: "Обложки через AI (OpenRouter vision)",
    category: "design",
  },
];

// ===== Hermes Plugins (16) =====
const PLUGINS = [
  { name: "designer-skills", count: 60, description: "UI/UX design system, критики, паттерны" },
  { name: "matt-pocock", count: 15, description: "TypeScript engineering: TDD, DDD, PRD, triage" },
  { name: "autonomous-ai-agents", count: 5, description: "Claude Code, Codex, OpenCode, супер-цели" },
  { name: "mcp", count: 1, description: "MCP servers (16 плагинов настроены)" },
  { name: "llm-response-parsing", count: 1, description: "JSON/XML/text парсинг ответов LLM" },
  { name: "llm-inference-ops", count: 1, description: "Inference провайдеров: latency, throughput" },
  { name: "gen-ai-provider-ops", count: 1, description: "Переключение между провайдерами" },
  { name: "huggingface-hub", count: 1, description: "Загрузка моделей и датасетов" },
  { name: "telegram-output-style", count: 1, description: "Telegram-style formatter" },
  { name: "kwork-gig-creation", count: 1, description: "Генерация кворков с правилами" },
  { name: "github", count: 3, description: "gh CLI: repo, PR, audit operations" },
  { name: "data-science", count: 1, description: "Jupyter live kernel для анализа" },
  { name: "mlops", count: 5, description: "ML ops, HF, OpenRouter, LLM ops" },
  { name: "note-taking", count: 3, description: "Obsidian, knowledge graphs" },
  { name: "productivity", count: 8, description: "Airtable, Google Workspace, Linear, Notion, Ocr" },
  { name: "creative", count: 7, description: "Algorithmic art, excalidraw, html-artifact" },
];

// ===== Категории =====
const CATEGORIES = [
  { id: "all", name: "Все", emoji: "🗂", color: "#7ee787" },
  { id: "ai", name: "AI-агенты", emoji: "🤖", color: "#a78bfa" },
  { id: "freelance", name: "Freelance", emoji: "💰", color: "#fbbf24" },
  { id: "telegram", name: "Telegram", emoji: "✈️", color: "#79c0ff" },
  { id: "code", name: "Code", emoji: "💻", color: "#f472b6" },
  { id: "deploy", name: "Deploy", emoji: "🚀", color: "#34d399" },
  { id: "docs", name: "Документы", emoji: "📄", color: "#fb923c" },
  { id: "design", name: "Design", emoji: "🎨", color: "#ec4899" },
  { id: "ru-market", name: "РФ рынок", emoji: "🇷🇺", color: "#60a5fa" },
];

// ===== Аналитика =====
const STATS = {
  mcps: MCPS.length,
  skills: SKILLS_GROUPS.reduce((s, g) => s + g.count, 0),
  plugins: PLUGINS.length,
  total: MCPS.length + SKILLS_GROUPS.reduce((s, g) => s + g.count, 0) + PLUGINS.length,
  tools: MCPS.reduce((s, m) => s + m.tools, 0),
};

window.AKC_DATA = { MCPS, SKILLS_GROUPS, PLUGINS, CATEGORIES, STATS };